artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1YlkKLCZjHGavry7jhtKjBLqSKOWBenIO/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

preprocess_data:
  save_path: artifacts/data_ingestion/preprocessed


training:
  root_dir: artifacts/training
  data_path: artifacts/data_ingestion/preprocessed
  results_dir: artifacts/training/results
  model_save_dir: artifacts/training/models
  model_type: SVM

evaluation:
  root_dir: artifacts/evaluation
  data_path: artifacts/data_ingestion/preprocessed
